### PR TITLE
fix: use ResourceLoader modules in serve mode (#2)

### LINKED ISSUE #2: serve mode does not use ResourceLoader modules
A big issue with the library as of now is possible deviation of what's being tested when using serve mode (`vite dev`) and what's actually ran by users when the script is placed onto a user JS file.

## Background

Currently, ResourceLoader (through `mw.loader.using`) only supports CommonJS imports (`require("module")`). On the other hand, Vite uses and encourages the use of ESM and targets `ESNext`. Currently, this plugin changes the output format into CJS when building (by changing [Rollup settings](https://github.com/ChlodAlejandro/vite-plugin-mediawiki-userscript/blob/master/src/plugin.ts#L69)), but this functionality is impossible to achieve when serving.

There now exists a discrepancy between ResourceLoader modules and modules sent to the browser in serve mode. One of these is due to the version: keeping the dependencies unlocked from version changes through a caret version selector means the installed version that's sent to the browser during dev could deviate from the version of the library currently on the MediaWiki core. For example, a dependent library could have Vue v3.3.6 whereas the MediaWiki core would have v3.3.9—a bug that is present in the dev server may be entirely fixed when built and saved on-wiki. The solution to this is just always pinning the package version, and that's something that must be done on a dependent projects' side (but we could add automated warnings for this prior to building).

The second, and more pressing issue, is that it is extremely difficult if not impossible to "hijack" `import`s in serve mode. In build mode, Rollup is set to completely avoid bundling specified external dependencies. If `using` is set to `[ "vue" ]`, it doesn't bundle Vue and instead emits a `require("vue")` call, which can be cleanly placed inside `mw.loader.using`'s function. In serve mode, there is no transformation to CJS occurring. Everything is still sent as ESM, and `import`s are used to load dependencies.

## Solutions
In trying to find a way to load ResourceLoader versions instead, here are some possible solutions I thought of/tried:

### Swap out the dependency
This is possible by using a custom `load` and `resolveId` hook. For consistency, let's use `vue` as the example library to be loaded from RL. `resolveId` is called, asking for a resolved version of `vue`. We intercept it, and replace it with a `mw.loader.using` call, which then exports whatever we loaded from MediaWiki.

Except this is impossible, because `exports` must be static. `module.exports` is not possible in ESM; every export must be statically analyzable. We also can't just toss `require("vue")` as a default export, because Vue doesn't have default exports. Once this "fake" module is loaded, the browser will try to resolve `{ createApp }`, but won't be able to find it since there'd only be a `default` export.

The way around this using normal Rollup is by using `this.getModuleInfo` to extract the exports of the package, and re-export those. Maybe inject exports for things that we know the MediaWiki version has too (like `createMwApp`). But accessing `exports` and `hasDefaultExport` is banned in Vite. The reasoning behind this is placed very obscurely in the Vite documentation:
> [...] some plugin hooks do not make sense in an unbundled dev server context.
> *— [Plugin API § Rollup Plugin Compatibility](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility). Vite Documentation.*

> Note that the [moduleParsed](https://rollupjs.org/plugin-development/#moduleparsed) hook is not called during dev, because Vite avoids full AST parses for better performance.
> *— [Plugin API § Universal Hooks](https://vitejs.dev/guide/api-plugin.html#universal-hooks). Vite Documentation.*

(n.b. `moduleParsed` would have [received information](https://rollupjs.org/plugin-development/#moduleparsed) that is returned by `getModuleInfo`, but `getModuleInfo` is bare-bones: it only returns an `id`, the resolved filename of the module being imported, and a blank `meta` object, because no AST parsing is done.)

We could attempt to resolve everything that the MediaWiki version of `vue` exports by loading the `load.php` result of the `vue` import, but we then have to mock a browser and pull out the `Object.keys` for `require("vue")` post-load, which greatly complicates things.
* We could do this as a build step, but this means releasing new package patch bumps whenever a MediaWiki core module is bumped (which we have to check every [train branch cut](https://wikitech.wikimedia.org/wiki/Deployments/Train)).
* We could do this process remotely and ask the library to pull down data from there (e.g. run this resolution process through CI, then publish the results on Toolforge), but this means requiring additional and external resources from the internet, a no-no in security.
* Neither of the two above address the problem of needing to "mock a browser". It is *possible* to do static analysis of the MediaWiki source (i.e. start from [resources/src/vue/index.js](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/master/resources/src/vue/index.js) and work our way there in resolution, but it adds an even worse layer of complexity: module resolution (and it has to be static!) of an IIFE.
* We **might not** be able to do this live, as we don't have access to the browser JS when resolving modules and, thus, we can't get the `Object.keys` as loaded from the remote.
  * We *could* use [client–server communication](https://vitejs.dev/guide/api-plugin.html#client-server-communication) to make the browser run `Object.keys(require("vue"))`, and then feed that back to the plugin to resolve the module. This *should* only be slow once: when the module is being loaded for the first time on the page. ResourceLoader caches the module, so subsequent `mw.loader.using` calls without navigation shouldn't require waiting for a web request, and we could also cache this on the plugin, while the dev server is loaded. **This is the most ideal; but it still needs to be tested.**

### Force use of CommonJS imports
This essentially makes the optimizations of Vite moot as it focuses on using ESM for improved performance. We might as well have used Webpack instead, which basically does this. It also goes against the Vite philosophy of keeping things as close to the original code as possible; something that we also need to value as Wikimedia script developers.

## Long-term thinking
This project was, first and foremost, an experiment. I'm really not sure if Vite is the proper way to go with this, and it seems this specific issue is a big hurdle for development. However, I went with it because (1) I was planning to use Vue anyway, so Vite was an obvious-ish choice, (2) it's much faster than Webpack, and (3) it has HMR — a must-have for userscript development, because loading Wikipedia over and over again with refreshes is a waste of bandwidth. If this is the way forward, this issue needs to be addressed, top priority.

## Fix condition
The following code should be valid:
```ts
import { createMwApp } from 'vue';
import App from './App.vue';

createMwApp( App ).mount( '#app' );
```
```vue
<template>
	<div id="codex-test-app">
		<h1>{{ $i18n( 'test-message' ).text() }}</h1>
		<cdx-button action="progressive" weight="primary">
			{{ $i18n( 'test-message-button' ).text() }}
		</cdx-button>
	</div>
</template>

<script lang="ts">
// lang="ts" should work because transpilation is done during build
import { defineComponent } from 'vue';
import { CdxButton } from '@wikimedia/codex';

export default defineComponent( {
	components: { CdxButton }
} );
</script>
```

### PR DESCRIPTION
**Pull request by sportshead**
The plugin now uses Vite/Rollup hooks `resolveId` and `load` in order to override the resolution of on-wiki dependencies. Any modules in the plugin's `options.using` will be overridden with a virtual module, that simply `export default`s the ResourceLoader module (i.e., emits `export default (await mw.loader.using("vue"))("vue")`. Any module that imports a RL module will have its import statements modified through the `transform` hook, in a method mimicking Rollup's [synthetic named exports feature](https://rollupjs.org/plugin-development/#synthetic-named-exports) (which is incompatible with Vite's import-analysis). For example:

```js
import { ref, createMwApp as createApp } from "vue";
```
will be transformed to
```js
import __mw_module1 from "/@id/__x00__mw-userscript:vue"; // `vue` would have been replaced by import-analysis with the virtual module
const { ref, createMwApp: createApp } = __mw_module1;
```

Additionally, an option `resourceLoaderDebugCookieAge?: number;` was added to the plugin allowing for users to tell the plugin to automatically set the [`resourceLoaderDebug` cookie](https://www.mediawiki.org/wiki/ResourceLoader/Architecture#Debug_mode) to enable RL debug mode. A falsy `resourceLoaderDebugCookieAge` stops the plugin from setting this cookie. This is needed in order for RL to load the development version of Vue, which contains the HMR functionality.

Fixes #2

### CODE REVIEW

File: src/plugin.ts [hunk 1]
```diff
@@ -83,24 +104,90 @@ export default function mediawikiUserscript( options: PluginOptions ): Plugin {
...
+				let code = '';
+				if ( options.resourceLoaderDebugCookieAge ) {
+					code += `document.cookie = "resourceLoaderDebug=2;max-age=${options.resourceLoaderDebugCookieAge}"\n`;
+				}
+				code += `const __mw_module = (await mw.loader.using(${JSON.stringify( name )}))(${JSON.stringify( name )});\n`;
+				code += 'export default __mw_module;\n';
+				if ( name === 'vue' ) {
+					code +=
+						'if (typeof __VUE_HMR_RUNTIME__ !== "object") {\n' +
+						'console.error("[vite-mw-userscript] ResourceLoader debug mode is not enabled. Without it, ' +
```
Comment (ChlodAlejandro) [inline src/plugin.ts:153]: This is almost always going to be wrong on first run if `resourceLoaderDebugCookieAge` is set, since the cookie wouldn't have been set at the time of page load (where Vue gets loaded, on some pages). Maybe we should use a different message for when it's set but `__VUE_HMR_RUNTIME__` is missing?

**Review by ChlodAlejandro — CHANGES_REQUESTED** [review]
Should probably also document the new configuration option and the underlying mechanism for it in the README, for documentation.

File: src/plugin.ts (hunk 1 above)
Comment (sportshead) [reply src/plugin.ts:153]: Fixed in 6812886

File: README.md [hunk 2]
```diff
@@ -70,6 +70,53 @@ Note that you should avoid importing styles from these modules, such as
 loaded by MediaWiki. Importing these styles would only cause additional
 overhead.
 
+### Development usage
+
+In Vite's `serve` mode, any import statements contianing modules in `using`
```
Comment (ChlodAlejandro) [inline README.md]: Looks good! One last change requested: typo on `contianing`, and I'll merge this in. 😄

**Review by ChlodAlejandro — CHANGES_REQUESTED** [review]

**Review by ChlodAlejandro — APPROVED** [review]
